### ISSUE TITLE
Automate/auto fill l10n copy for words like dismiss, remove this, etc. (+ pre-populate fields with l10n language based on locale selection)

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#881] opened 2018-12-10 18:34 UTC
1) To reduce manual error, if we can autopopulate certain l10n copy for words that we will always use such as:

Dismiss
Remove this 

2) If possible, pre-populate fields with l10n copy based on locale selection

**Comment by glogiotatidis** [comment] 2018-12-10 18:46
See also #757

**Comment by glogiotatidis** [comment] 2019-05-22 11:46
Note to self:

- Maybe we can create a special widget with a drop-down and the `<input>` field. do the auto-population with JS

**Comment by glogiotatidis** [comment] 2019-05-22 11:47
See also #749

**Comment by glogiotatidis** [comment] 2019-07-05 06:55
Closing this as duplicate of #757

**Closed by glogiotatidis** 2019-07-05 06:55 UTC
Labels: :crown: Admin
