### ISSUE TITLE
Automate/append UTM parameters 

### ISSUE THREAD

**Issue by jkt230** [mozmeao/snippets-service#880] opened 2018-12-10 18:33 UTC
We typically always use the same utm_parameters (with a few variables):

Example:
utm_source=desktop-snippet&utm_medium=snippet&utm_campaign=LiveNationConcert&utm_term=9820&utm_content=REL_ESR

These always stay the same:
utm_source=desktop-snippet
utm_medium=snippet

Variables:
utm_campaign 
utm_term [based on snippet ID, I think this automatically gets autopopulated]
utm_content

**Comment by glogiotatidis** [comment] 2018-12-10 18:50
> utm_content

Can you please explain this one too?

**Comment by jkt230** [comment] 2018-12-10 19:25
In the past we've used it if we had different copy variations like V1 or V2. Michelle has been using it to mark which channels the snippet would run in like REL_ESR or Beta or DEV, etc. 

We haven't quite landed on exactly how we should use them moving forward but this shouldn't affect this issue right?

**Comment by glogiotatidis** [comment] 2019-01-15 14:14
Duplicate of #752

**Closed by glogiotatidis** 2019-01-15 14:14 UTC
